import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { Control } from "./Control";

export const metadata: Metadata = {
  title: "github",
  description: "Generated by Minihallo",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const topics = await getTopics();
  const res = await fetch(process.env.NEXT_PUBLIC_API_URL + 'topics', {cache:'no-cache'});
  const topics = await res.json();
  return (
    <html>
      <body>
        <h1><a href="/">home</a></h1>
        <ol>
          {topics.map((topic: any) => {
              return <li key={topic.id}>
                <Link href={`/read/${topic.id}`}>{topic.title}</Link>
              </li>
          })}
        </ol>
        {children}
        <Control />
      </body>
    </html>
  );
}
